version: "2"
linters:
  settings:
    lll:
      line-length: 90
    revive:
      rules:
        - name: unused-parameter
          disabled: true
        - name: error-strings
          disabled: true
        - name: indent-error-flow
          disabled: true
  enable:
    - govet
    - revive
    - staticcheck
    - exhaustive
    - lll
    - misspell
    - dupword
