version: "2"
linters:
  settings:
    lll:
      line-length: 90
    revive:
      rules:
        - name: unused-parameter
          disabled: true
  enable:
    - govet
    - revive
    - staticcheck
    - lll
    - misspell
    - dupword
  disable:
    - errcheck
